"""Claude labels per distinct creative for the 10% (competitor 3, FR) run; groups = distinct (format, copy, headline, cta, transcript) in order of first appearance.
(hook, angle, offer, awareness 0-4, cta_strength 0-4, ugc yes/no/unknown)"""
G = [
 ('pain_point', 'pain', 'direct_offer', 1, 3, 'yes'),
 ('question', 'desire', 'direct_offer', 2, 3, 'yes'),
 ('bold_claim', 'authority', 'direct_offer', 2, 3, 'no'),
 ('question', 'desire', 'direct_offer', 2, 3, 'no'),
 ('bold_claim', 'desire', 'direct_offer', 2, 3, 'unknown'),
 ('question', 'desire', 'direct_offer', 2, 3, 'no'),
 ('curiosity', 'desire', 'direct_offer', 2, 3, 'yes'),
 ('curiosity', 'desire', 'direct_offer', 2, 3, 'yes'),
 ('question', 'desire', 'direct_offer', 2, 3, 'no'),
 ('bold_claim', 'comparison', 'direct_offer', 2, 3, 'yes'),
 ('curiosity', 'desire', 'direct_offer', 2, 3, 'yes'),
 ('question', 'desire', 'direct_offer', 2, 3, 'no'),
 ('question', 'desire', 'direct_offer', 2, 3, 'no'),
 ('question', 'desire', 'direct_offer', 2, 3, 'yes'),
 ('curiosity', 'curiosity', 'direct_offer', 2, 3, 'yes'),
 ('curiosity', 'desire', 'direct_offer', 2, 3, 'yes'),
 ('question', 'desire', 'direct_offer', 2, 3, 'no'),
 ('question', 'desire', 'direct_offer', 2, 3, 'yes'),
 ('curiosity', 'desire', 'direct_offer', 2, 3, 'yes'),
 ('pain_point', 'desire', 'direct_offer', 2, 3, 'yes'),
 ('question', 'desire', 'direct_offer', 2, 3, 'yes'),
 ('question', 'desire', 'direct_offer', 2, 3, 'unknown'),
 ('pain_point', 'pain', 'direct_offer', 1, 3, 'no'),
 ('question', 'desire', 'direct_offer', 2, 3, 'yes'),
 ('curiosity', 'desire', 'direct_offer', 2, 3, 'yes'),
 ('curiosity', 'curiosity', 'direct_offer', 2, 3, 'yes'),
]
