"""Claude labels per distinct creative for the full ibotta (US) run; groups = distinct (format, copy, headline, cta, transcript) in order of first appearance.
(hook, angle, offer, awareness 0-4, cta_strength 0-4, ugc yes/no/unknown)"""
G = [
 ('social_proof', 'social_proof', 'direct_offer', 3, 1, 'yes'),
 ('curiosity', 'curiosity', 'none', 3, 0, 'no'),
 ('question', 'desire', 'direct_offer', 2, 3, 'yes'),
 ('question', 'curiosity', 'none', 3, 0, 'no'),
 ('question', 'desire', 'direct_offer', 2, 3, 'yes'),
 ('curiosity', 'desire', 'direct_offer', 2, 3, 'yes'),
 ('pain_point', 'desire', 'direct_offer', 3, 1, 'no'),
 ('bold_claim', 'desire', 'direct_offer', 3, 1, 'yes'),
 ('question', 'desire', 'direct_offer', 2, 3, 'yes'),
 ('question', 'desire', 'direct_offer', 2, 2, 'yes'),
 ('bold_claim', 'desire', 'direct_offer', 3, 1, 'yes'),
 ('bold_claim', 'desire', 'direct_offer', 3, 2, 'no'),
 ('bold_claim', 'desire', 'direct_offer', 3, 1, 'yes'),
 ('curiosity', 'desire', 'direct_offer', 3, 2, 'yes'),
 ('bold_claim', 'desire', 'direct_offer', 3, 1, 'unknown'),
 ('question', 'desire', 'direct_offer', 2, 3, 'yes'),
 ('question', 'desire', 'direct_offer', 2, 2, 'unknown'),
 ('question', 'desire', 'direct_offer', 2, 2, 'yes'),
 ('bold_claim', 'desire', 'direct_offer', 2, 3, 'no'),
 ('bold_claim', 'desire', 'direct_offer', 2, 3, 'no'),
 ('question', 'pain', 'direct_offer', 1, 2, 'no'),
 ('bold_claim', 'desire', 'direct_offer', 3, 1, 'no'),
 ('question', 'desire', 'direct_offer', 2, 2, 'yes'),
 ('question', 'desire', 'direct_offer', 2, 3, 'yes'),
 ('curiosity', 'curiosity', 'direct_offer', 3, 1, 'yes'),
 ('bold_claim', 'desire', 'direct_offer', 2, 2, 'no'),
 ('question', 'desire', 'direct_offer', 2, 2, 'yes'),
 ('bold_claim', 'desire', 'direct_offer', 3, 2, 'no'),
 ('question', 'desire', 'direct_offer', 2, 2, 'yes'),
 ('bold_claim', 'desire', 'direct_offer', 2, 2, 'no'),
 ('bold_claim', 'desire', 'direct_offer', 2, 3, 'no'),
 ('bold_claim', 'desire', 'direct_offer', 3, 1, 'yes'),
 ('how_to', 'desire', 'direct_offer', 2, 2, 'yes'),
 ('question', 'pain', 'direct_offer', 1, 3, 'yes'),
 ('question', 'desire', 'direct_offer', 2, 3, 'yes'),
 ('bold_claim', 'desire', 'direct_offer', 3, 1, 'no'),
 ('question', 'desire', 'direct_offer', 2, 3, 'yes'),
 ('how_to', 'desire', 'direct_offer', 2, 2, 'yes'),
 ('bold_claim', 'desire', 'direct_offer', 2, 2, 'yes'),
 ('curiosity', 'desire', 'direct_offer', 2, 3, 'yes'),
 ('bold_claim', 'desire', 'direct_offer', 3, 1, 'yes'),
]
